on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs: 
      out: ${{ steps.set_out.outputs.out }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: test setting env with fsx
      id: test
      run: |
        dotnet fsi test_env.fsx
    - name: set output
      id: set_out
      run: |
        echo $SCRIPT_OUTPUT
        echo "out=$SCRIPT_OUTPUT" >> $GITHUB_OUTPUT

  print:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: print
      run: |
        echo ${{ needs.test.outputs.out}}